"""empty message

Revision ID: aa4c5cb81c94
Revises: abd5fa6521f3
Create Date: 2023-11-10 20:04:59.907446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4c5cb81c94'
down_revision = 'abd5fa6521f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casting_time', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('casting_time')

    # ### end Alembic commands ###
